# Form implementation generated from reading ui file 'Kayit.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(350, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(350, 250))
        Form.setMaximumSize(QtCore.QSize(350, 250))
        Form.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setStyleSheet("\n"
"border-radius: 20px;\n"
"background-color: rgb(35, 35, 35);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(320, 100))
        self.frame_2.setMaximumSize(QtCore.QSize(320, 100))
        self.frame_2.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_2.sizePolicy().hasHeightForWidth())
        self.stackedWidget_2.setSizePolicy(sizePolicy)
        self.stackedWidget_2.setMinimumSize(QtCore.QSize(50, 70))
        self.stackedWidget_2.setMaximumSize(QtCore.QSize(250, 70))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.save_name = QtWidgets.QLineEdit(parent=self.page_3)
        self.save_name.setGeometry(QtCore.QRect(60, 30, 121, 25))
        self.save_name.setStyleSheet("border: 3px solid;\n"
"border-radius: 5px;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(61, 61, 61);\n"
"font: 75 12pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);")
        self.save_name.setObjectName("save_name")
        self.label = QtWidgets.QLabel(parent=self.page_3)
        self.label.setGeometry(QtCore.QRect(60, 10, 181, 20))
        self.label.setStyleSheet("font: 75 11pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget_2.addWidget(self.page_4)
        self.horizontalLayout_3.addWidget(self.stackedWidget_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(320, 100))
        self.frame_3.setMaximumSize(QtCore.QSize(320, 100))
        self.frame_3.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(23, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btn_save = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_save.setMinimumSize(QtCore.QSize(100, 45))
        self.btn_save.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_save.setStyleSheet("\n"
"QPushButton {\n"
"  background-color: rgb(35, 35, 35);\n"
"  color: rgb(85, 85, 85);\n"
"  font-weight: 600;\n"
"  font: 75 12pt \"FreeSans\";\n"
"  text-align: cente;\n"
"  border-radius: 5px;\n"
"  padding: 5px 15px;\n"
"  outline: 0px;\n"
"  image: url(:/images/Desktop/Asıl proje/m_home.png);\n"
"\n"
"  image-size: 30px 30px;\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  color: rgb(255, 255, 255);\n"
"  image: url(:/images/Desktop/Asıl proje/icons8-home-26.png);\n"
"  background-color: rgb(0, 0, 0);\n"
"  border-radius: 20px;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  color: rgb(255, 255, 255);\n"
"  image: url(:/images/Desktop/Asıl proje/icons8-home-26.png);\n"
"  background-color: rgb(0, 0, 0);\n"
"  border-radius: 20px;\n"
"\n"
"}\n"
"    \n"
"    ")
        self.btn_save.setIconSize(QtCore.QSize(45, 45))
        self.btn_save.setCheckable(True)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_4.addWidget(self.btn_save)
        spacerItem1 = QtWidgets.QSpacerItem(23, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btn_save_2 = QtWidgets.QPushButton(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save_2.sizePolicy().hasHeightForWidth())
        self.btn_save_2.setSizePolicy(sizePolicy)
        self.btn_save_2.setMinimumSize(QtCore.QSize(100, 45))
        self.btn_save_2.setStyleSheet("\n"
"QPushButton {\n"
"  background-color: rgb(35, 35, 35);\n"
"  color: rgb(85, 85, 85);\n"
"  font-weight: 600;\n"
"  font: 75 12pt \"FreeSans\";\n"
"  text-align: center;\n"
"  border-radius: 5px;\n"
"  padding: 5px 15px;\n"
"  outline: 0px;\n"
"  image: url(:/images/Desktop/Asıl proje/m_home.png);\n"
"\n"
"  image-size: 30px 30px;\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  color: rgb(255, 255, 255);\n"
"  image: url(:/images/Desktop/Asıl proje/icons8-home-26.png);\n"
"  background-color: rgb(0, 0, 0);\n"
"  border-radius: 20px;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  color: rgb(255, 255, 255);\n"
"  image: url(:/images/Desktop/Asıl proje/icons8-home-26.png);\n"
"  background-color: rgb(0, 0, 0);\n"
"  border-radius: 20px;\n"
"\n"
"}\n"
"    \n"
"    ")
        self.btn_save_2.setIconSize(QtCore.QSize(45, 45))
        self.btn_save_2.setCheckable(True)
        self.btn_save_2.setObjectName("btn_save_2")
        self.horizontalLayout_4.addWidget(self.btn_save_2)
        spacerItem2 = QtWidgets.QSpacerItem(23, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(parent=self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(320, 100))
        self.frame_5.setMaximumSize(QtCore.QSize(320, 110))
        self.frame_5.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_2.setStyleSheet("font: 75 12pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setIndent(-1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(320, 110))
        self.frame_6.setMaximumSize(QtCore.QSize(320, 110))
        self.frame_6.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(102, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.btn_makine_bilgi_6 = QtWidgets.QPushButton(parent=self.frame_6)
        self.btn_makine_bilgi_6.setMinimumSize(QtCore.QSize(90, 50))
        self.btn_makine_bilgi_6.setStyleSheet("\n"
"QPushButton {\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(85, 85, 85);\n"
"  font-weight: 600;\n"
"  font: 75 12pt \"FreeSans\";\n"
"\n"
"  border-radius: 20px;\n"
"  padding: 5px 15px;\n"
"  outline: 0px;\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  color: rgb(255, 255, 255);\n"
"\n"
"  background-color: rgb(0, 170, 0);\n"
"  border-radius: 20px;\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  color: rgb(255, 255, 255);\n"
"\n"
"  background-color: rgb(0, 0, 0);\n"
"  border-radius: 20px;\n"
"\n"
"}\n"
"    \n"
"    ")
        self.btn_makine_bilgi_6.setIconSize(QtCore.QSize(45, 45))
        self.btn_makine_bilgi_6.setObjectName("btn_makine_bilgi_6")
        self.horizontalLayout_7.addWidget(self.btn_makine_bilgi_6)
        spacerItem4 = QtWidgets.QSpacerItem(101, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.page_2)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_9 = QtWidgets.QFrame(parent=self.page_5)
        self.frame_9.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(120, 17))
        self.label_5.setMaximumSize(QtCore.QSize(120, 17))
        self.label_5.setStyleSheet("font: 75 12pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(120, 17))
        self.label_6.setMaximumSize(QtCore.QSize(120, 17))
        self.label_6.setStyleSheet("font: 75 12pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.frame_7 = QtWidgets.QFrame(parent=self.page_5)
        self.frame_7.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem7 = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.marka_secim = QtWidgets.QComboBox(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.marka_secim.sizePolicy().hasHeightForWidth())
        self.marka_secim.setSizePolicy(sizePolicy)
        self.marka_secim.setMinimumSize(QtCore.QSize(100, 20))
        self.marka_secim.setMaximumSize(QtCore.QSize(100, 20))
        self.marka_secim.setStyleSheet("QComboBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(252, 160, 36, 0), stop:1 rgba(255, 255, 0, 0));\n"
"    border: 0px solid;\n"
"    font: 75 12pt \"FreeSans\";\n"
"}\n"
"")
        self.marka_secim.setObjectName("marka_secim")
        self.horizontalLayout_9.addWidget(self.marka_secim)
        spacerItem8 = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(parent=self.page_5)
        self.frame_8.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem9 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.btn_makine_bilgi_7 = QtWidgets.QPushButton(parent=self.frame_8)
        self.btn_makine_bilgi_7.setMinimumSize(QtCore.QSize(90, 50))
        self.btn_makine_bilgi_7.setStyleSheet("\n"
"QPushButton {\n"
"  background-color: rgb(35, 35, 35);\n"
"  color: rgb(85, 85, 85);\n"
"  font-weight: 600;\n"
"  font: 75 12pt \"FreeSans\";\n"
"\n"
"  border-radius: 20px;\n"
"  padding: 5px 15px;\n"
"  outline: 0px;\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  color: rgb(255, 255, 255);\n"
"\n"
"  background-color: rgb(0, 170, 0);\n"
"  border-radius: 20px;\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  color: rgb(255, 255, 255);\n"
"\n"
"  background-color: rgb(0, 170, 0);\n"
"  border-radius: 20px;\n"
"\n"
"}\n"
"    \n"
"    ")
        self.btn_makine_bilgi_7.setIconSize(QtCore.QSize(45, 45))
        self.btn_makine_bilgi_7.setObjectName("btn_makine_bilgi_7")
        self.horizontalLayout_10.addWidget(self.btn_makine_bilgi_7)
        spacerItem10 = QtWidgets.QSpacerItem(31, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.btn_makine_bilgi_8 = QtWidgets.QPushButton(parent=self.frame_8)
        self.btn_makine_bilgi_8.setMinimumSize(QtCore.QSize(90, 50))
        self.btn_makine_bilgi_8.setStyleSheet("\n"
"QPushButton {\n"
"  background-color: rgb(35, 35, 35);\n"
"  color: rgb(85, 85, 85);\n"
"  font-weight: 600;\n"
"  font: 75 12pt \"FreeSans\";\n"
"\n"
"  border-radius: 20px;\n"
"  padding: 5px 15px;\n"
"  outline: 0px;\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  color: rgb(255, 255, 255);\n"
"\n"
"  background-color: rgb(0, 170, 0);\n"
"  border-radius: 20px;\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  color: rgb(255, 255, 255);\n"
"\n"
"  background-color: rgb(0, 170, 0);\n"
"  border-radius: 20px;\n"
"\n"
"}\n"
"    \n"
"    ")
        self.btn_makine_bilgi_8.setIconSize(QtCore.QSize(45, 45))
        self.btn_makine_bilgi_8.setObjectName("btn_makine_bilgi_8")
        self.horizontalLayout_10.addWidget(self.btn_makine_bilgi_8)
        spacerItem11 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_4 = QtWidgets.QFrame(parent=self.page_6)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_10.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.label_7 = QtWidgets.QLabel(parent=self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(120, 17))
        self.label_7.setMaximumSize(QtCore.QSize(120, 17))
        self.label_7.setStyleSheet("font: 75 12pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.label_4 = QtWidgets.QLabel(parent=self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(120, 17))
        self.label_4.setMaximumSize(QtCore.QSize(120, 17))
        self.label_4.setStyleSheet("font: 75 12pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem13)
        self.verticalLayout_4.addWidget(self.frame_10)
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_12.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem14 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem14)
        self.stackedWidget_3 = QtWidgets.QStackedWidget(parent=self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_3.sizePolicy().hasHeightForWidth())
        self.stackedWidget_3.setSizePolicy(sizePolicy)
        self.stackedWidget_3.setMinimumSize(QtCore.QSize(110, 40))
        self.stackedWidget_3.setMaximumSize(QtCore.QSize(110, 40))
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.stackedWidget_3.addWidget(self.page_7)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.makine_secim_2 = QtWidgets.QComboBox(parent=self.page_9)
        self.makine_secim_2.setGeometry(QtCore.QRect(0, 10, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makine_secim_2.sizePolicy().hasHeightForWidth())
        self.makine_secim_2.setSizePolicy(sizePolicy)
        self.makine_secim_2.setMinimumSize(QtCore.QSize(100, 20))
        self.makine_secim_2.setMaximumSize(QtCore.QSize(100, 20))
        self.makine_secim_2.setStyleSheet("QComboBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(252, 160, 36, 0), stop:1 rgba(255, 255, 0, 0));\n"
"    border: 0px solid;\n"
"    font: 75 12pt \"FreeSans\";\n"
"}\n"
"")
        self.makine_secim_2.setObjectName("makine_secim_2")
        self.stackedWidget_3.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.makine_secim_3 = QtWidgets.QComboBox(parent=self.page_10)
        self.makine_secim_3.setGeometry(QtCore.QRect(0, 10, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makine_secim_3.sizePolicy().hasHeightForWidth())
        self.makine_secim_3.setSizePolicy(sizePolicy)
        self.makine_secim_3.setMinimumSize(QtCore.QSize(100, 20))
        self.makine_secim_3.setMaximumSize(QtCore.QSize(100, 20))
        self.makine_secim_3.setStyleSheet("QComboBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(252, 160, 36, 0), stop:1 rgba(255, 255, 0, 0));\n"
"    border: 0px solid;\n"
"    font: 75 12pt \"FreeSans\";\n"
"}\n"
"")
        self.makine_secim_3.setObjectName("makine_secim_3")
        self.stackedWidget_3.addWidget(self.page_10)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.makine_secim_5 = QtWidgets.QComboBox(parent=self.page_11)
        self.makine_secim_5.setGeometry(QtCore.QRect(0, 10, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makine_secim_5.sizePolicy().hasHeightForWidth())
        self.makine_secim_5.setSizePolicy(sizePolicy)
        self.makine_secim_5.setMinimumSize(QtCore.QSize(100, 20))
        self.makine_secim_5.setMaximumSize(QtCore.QSize(100, 20))
        self.makine_secim_5.setStyleSheet("QComboBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(252, 160, 36, 0), stop:1 rgba(255, 255, 0, 0));\n"
"    border: 0px solid;\n"
"    font: 75 12pt \"FreeSans\";\n"
"}\n"
"")
        self.makine_secim_5.setObjectName("makine_secim_5")
        self.stackedWidget_3.addWidget(self.page_11)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.makine_secim_6 = QtWidgets.QComboBox(parent=self.page_12)
        self.makine_secim_6.setGeometry(QtCore.QRect(0, 10, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makine_secim_6.sizePolicy().hasHeightForWidth())
        self.makine_secim_6.setSizePolicy(sizePolicy)
        self.makine_secim_6.setMinimumSize(QtCore.QSize(100, 20))
        self.makine_secim_6.setMaximumSize(QtCore.QSize(100, 20))
        self.makine_secim_6.setStyleSheet("QComboBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(252, 160, 36, 0), stop:1 rgba(255, 255, 0, 0));\n"
"    border: 0px solid;\n"
"    font: 75 12pt \"FreeSans\";\n"
"}\n"
"")
        self.makine_secim_6.setObjectName("makine_secim_6")
        self.stackedWidget_3.addWidget(self.page_12)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.makine_secim_7 = QtWidgets.QComboBox(parent=self.page_13)
        self.makine_secim_7.setGeometry(QtCore.QRect(0, 10, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makine_secim_7.sizePolicy().hasHeightForWidth())
        self.makine_secim_7.setSizePolicy(sizePolicy)
        self.makine_secim_7.setMinimumSize(QtCore.QSize(100, 20))
        self.makine_secim_7.setMaximumSize(QtCore.QSize(100, 20))
        self.makine_secim_7.setStyleSheet("QComboBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(252, 160, 36, 0), stop:1 rgba(255, 255, 0, 0));\n"
"    border: 0px solid;\n"
"    font: 75 12pt \"FreeSans\";\n"
"}\n"
"")
        self.makine_secim_7.setObjectName("makine_secim_7")
        self.stackedWidget_3.addWidget(self.page_13)
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.makine_secim_8 = QtWidgets.QComboBox(parent=self.page_14)
        self.makine_secim_8.setGeometry(QtCore.QRect(0, 10, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makine_secim_8.sizePolicy().hasHeightForWidth())
        self.makine_secim_8.setSizePolicy(sizePolicy)
        self.makine_secim_8.setMinimumSize(QtCore.QSize(100, 20))
        self.makine_secim_8.setMaximumSize(QtCore.QSize(100, 20))
        self.makine_secim_8.setStyleSheet("QComboBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(252, 160, 36, 0), stop:1 rgba(255, 255, 0, 0));\n"
"    border: 0px solid;\n"
"    font: 75 12pt \"FreeSans\";\n"
"}\n"
"")
        self.makine_secim_8.setObjectName("makine_secim_8")
        self.stackedWidget_3.addWidget(self.page_14)
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setObjectName("page_15")
        self.makine_secim_9 = QtWidgets.QComboBox(parent=self.page_15)
        self.makine_secim_9.setGeometry(QtCore.QRect(0, 10, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makine_secim_9.sizePolicy().hasHeightForWidth())
        self.makine_secim_9.setSizePolicy(sizePolicy)
        self.makine_secim_9.setMinimumSize(QtCore.QSize(100, 20))
        self.makine_secim_9.setMaximumSize(QtCore.QSize(100, 20))
        self.makine_secim_9.setStyleSheet("QComboBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(252, 160, 36, 0), stop:1 rgba(255, 255, 0, 0));\n"
"    border: 0px solid;\n"
"    font: 75 12pt \"FreeSans\";\n"
"}\n"
"")
        self.makine_secim_9.setObjectName("makine_secim_9")
        self.stackedWidget_3.addWidget(self.page_15)
        self.page_16 = QtWidgets.QWidget()
        self.page_16.setObjectName("page_16")
        self.makine_secim = QtWidgets.QComboBox(parent=self.page_16)
        self.makine_secim.setGeometry(QtCore.QRect(0, 10, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makine_secim.sizePolicy().hasHeightForWidth())
        self.makine_secim.setSizePolicy(sizePolicy)
        self.makine_secim.setMinimumSize(QtCore.QSize(100, 20))
        self.makine_secim.setMaximumSize(QtCore.QSize(100, 20))
        self.makine_secim.setStyleSheet("QComboBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(252, 160, 36, 0), stop:1 rgba(255, 255, 0, 0));\n"
"    border: 0px solid;\n"
"    font: 75 12pt \"FreeSans\";\n"
"}\n"
"")
        self.makine_secim.setObjectName("makine_secim")
        self.stackedWidget_3.addWidget(self.page_16)
        self.horizontalLayout_13.addWidget(self.stackedWidget_3)
        spacerItem15 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem15)
        self.verticalLayout_4.addWidget(self.frame_12)
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_11.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem16 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem16)
        self.btn_makine_bilgi_9 = QtWidgets.QPushButton(parent=self.frame_11)
        self.btn_makine_bilgi_9.setMinimumSize(QtCore.QSize(90, 50))
        self.btn_makine_bilgi_9.setStyleSheet("\n"
"QPushButton {\n"
"  background-color: rgb(35, 35, 35);\n"
"  color: rgb(85, 85, 85);\n"
"  font-weight: 600;\n"
"  font: 75 12pt \"FreeSans\";\n"
"\n"
"  border-radius: 20px;\n"
"  padding: 5px 15px;\n"
"  outline: 0px;\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  color: rgb(255, 255, 255);\n"
"\n"
"  background-color: rgb(0, 170, 0);\n"
"  border-radius: 20px;\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  color: rgb(255, 255, 255);\n"
"\n"
"  background-color: rgb(0, 170, 0);\n"
"  border-radius: 20px;\n"
"\n"
"}\n"
"    \n"
"    ")
        self.btn_makine_bilgi_9.setIconSize(QtCore.QSize(45, 45))
        self.btn_makine_bilgi_9.setObjectName("btn_makine_bilgi_9")
        self.horizontalLayout_12.addWidget(self.btn_makine_bilgi_9)
        spacerItem17 = QtWidgets.QSpacerItem(31, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem17)
        self.btn_makine_bilgi_10 = QtWidgets.QPushButton(parent=self.frame_11)
        self.btn_makine_bilgi_10.setMinimumSize(QtCore.QSize(90, 50))
        self.btn_makine_bilgi_10.setStyleSheet("\n"
"QPushButton {\n"
"  background-color: rgb(35, 35, 35);\n"
"  color: rgb(85, 85, 85);\n"
"  font-weight: 600;\n"
"  font: 75 12pt \"FreeSans\";\n"
"\n"
"  border-radius: 20px;\n"
"  padding: 5px 15px;\n"
"  outline: 0px;\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  color: rgb(255, 255, 255);\n"
"\n"
"  background-color: rgb(0, 170, 0);\n"
"  border-radius: 20px;\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  color: rgb(255, 255, 255);\n"
"\n"
"  background-color: rgb(0, 170, 0);\n"
"  border-radius: 20px;\n"
"\n"
"}\n"
"    \n"
"    ")
        self.btn_makine_bilgi_10.setIconSize(QtCore.QSize(45, 45))
        self.btn_makine_bilgi_10.setObjectName("btn_makine_bilgi_10")
        self.horizontalLayout_12.addWidget(self.btn_makine_bilgi_10)
        spacerItem18 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem18)
        self.verticalLayout_4.addWidget(self.frame_11)
        self.horizontalLayout_5.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.page_6)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_3.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Kayıt ismini giriniz"))
        self.btn_save.setText(_translate("Form", "Kaydet"))
        self.btn_save_2.setText(_translate("Form", "İptal"))
        self.label_2.setText(_translate("Form", "AAAAA"))
        self.btn_makine_bilgi_6.setText(_translate("Form", "Kapat"))
        self.label_5.setText(_translate("Form", "Önceki kayıt ismi"))
        self.label_6.setText(_translate("Form", "aaaaa"))
        self.btn_makine_bilgi_7.setText(_translate("Form", "Kaydet"))
        self.btn_makine_bilgi_8.setText(_translate("Form", "İptal"))
        self.label_7.setText(_translate("Form", "Önceki kayıt ismi"))
        self.label_4.setText(_translate("Form", "aaaaa"))
        self.btn_makine_bilgi_9.setText(_translate("Form", "Kaydet"))
        self.btn_makine_bilgi_10.setText(_translate("Form", "İptal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
